### ISSUE TITLE
Cache dependencies

### ISSUE THREAD

**Issue by sdruskat** [dieghernan/cff-validator#1]
Hi @dieghernan, thanks for a great project!

I've found that using the example setup you provide in `README.md`, the dependencies for your script are downloaded and installed afresh every time the action is run, which increases runtime for users.

I'm not sure if there is perhaps a reason for doing this, and I haven't had a very close look at `action.yml` (and I'm not an experienced R user at all), but perhaps the dependencies could be cached as well? Or if they are, the example could be amended to enable caching?

Thanks!

**Comment by dieghernan** [comment]
Hi @sdruskat ! 

First of all, thanks for your feedback. The dependencies should be catched after the first run of the action. I prepared a little repo for testing:

https://github.com/dieghernan/cfftest/

On the [Actions Tab](https://github.com/dieghernan/cfftest/actions/workflows/cff-validator.yml) I see:

## With `uses: dieghernan/cff-validator@v1`
**CITATION.cff 1:  2m 51s** - Here dependencies are installed and cached.
**CITATION.cff 2:  57s** - After the first run, dependencies are already cached.

I also run CITATION.cff 3 & CITATION.cff 4 with the dev version of the action `uses: dieghernan/cff-validator@main`, although
the changes since v1 has been quite minor:

## With `uses: dieghernan/cff-validator@main`
**CITATION.cff 3:  56s**
**CITATION.cff 4:  45s**

So after the first fun the times has decreased notabily.  At this point I don't really know how to improve that running times.

What I would do is to change the action version to **`dieghernan/cff-validator@main`** as it seems that the improvement after caching is noticeable.

**Comment by sdruskat** [comment]
Thanks. It seems from the logs that the R dependencies are still actively downloaded and installed, but perhaps this isn't something that can be cached well, or that the logs don't represent that this process uses cached dependencies actually.

In any case, I think < 1m for running this action is fine, so will close this issue :).

Thanks for updating the docs to use `main`.
